spring:
  ai:
    mcp:
      server:
        name: location-mcp-sse
        version: 1.0.0
        type: SYNC
        instructions: "This server provides meeting location suggestions based on user preferences and can book rooms at the location."
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  main:
    banner-mode: console
    web-application-type: servlet
  # Static resources configuration
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
      add-mappings: true
  mvc:
    static-path-pattern: /**

server:
  port: 8081
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false  # Set to true in production with HTTPS
        http-only: true
        name: LOCATION_MCP_SESSION


logging:
  level:
    com.embabel: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure.security: INFO
    org.rag4j.meetingplanner: INFO
    root: INFO

