spring:
  ai:
    mcp:
      server:
        name: location-mcp-sse
        version: 1.0.0
        type: SYNC
        instructions: "This server provides meeting location suggestions based on user preferences and can book rooms at the location."
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
  main:
    banner-mode: console
    web-application-type: servlet
  # Static resources configuration
  web:
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
      add-mappings: true
  mvc:
    static-path-pattern: /**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

server:
  port: 8081

logging:
  level:
    com.embabel: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.client: DEBUG
    org.rag4j.meetingplanner.webapp.SessionDebugFilter: INFO
    root: INFO

