POST http://localhost:8080/create-meeting
Content-Type: application/x-www-form-urlencoded

title = Team Planning Meeting &
description = Weekly planning session to discuss project priorities and roadmap &
date = 2025-09-01 &
startTime = 10:00 &
durationMinutes = 60 &
location = Conference Room A &
participants = jettro@rag4j.org,daniel@rag4j.org &
suggestOptimalTime = true &
generateAgenda = true &
sendReminders = true

###
POST http://localhost:8080/create-meeting
Content-Type: application/x-www-form-urlencoded

title = Workshop discuss timelines &
description = Start the preparation for the workshop &
date = 2025-09-01 &
startTime = 13:00 &
durationMinutes = 120 &
location = Conference Room A &
participants = jettro@rag4j.org,daniel@rag4j.org &
suggestOptimalTime = true &
generateAgenda = true &
sendReminders = true

###
POST http://localhost:8080/create-meeting
Content-Type: application/x-www-form-urlencoded

title = Standup project &
description = Recurring appointment for the standup &
date = 2025-09-01 &
startTime = 10:15 &
durationMinutes = 15 &
location = Conference Room A &
participants = jettro@rag4j.org,daniel@rag4j.org &,joey@rag4j.org
suggestOptimalTime = true &
generateAgenda = true &
sendReminders = true

###

GET http://localhost:8080/meetings


###