spring:
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        stdio:
#          servers-configuration: classpath:mcp-servers-config.json
          connections:
            time:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/time
                - --local-timezone=America/New_York
            location:
              command: java
              args:
                - -Dspring.ai.mcp.server.stdio=true
                - -Dspring.main.web-application-type=none
                - -Dspring.main.banner-mode=off
                - -Dlogging.pattern.console=
                - -jar
                - "${LOCATION_MCP_JAR:${user.dir}/location-mcp/target/location-mcp-1.0.0-SNAPSHOT.jar}"
