spring:
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        stdio:
          connections:
            time:
              command: docker
              args:
                - run
                - -i
                - --rm
                - mcp/time
                - --local-timezone=America/New_York
        sse:
          connections:
            location-mcp:
              url: http://localhost:8081
              sse-endpoint: /sse

  autoconfigure:
    exclude:
      - org.springframework.ai.mcp.client.autoconfigure.SseWebFluxTransportAutoConfiguration

embabel:
  models:
    default-llm: gpt-5-mini
    llms:
      best: gpt-5
      balanced: gpt-5-mini
