server:
  port: 8080
  
spring:
  application:
    name: meeting-planner-web-app

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Embabel Agent Configuration
embabel:
  agent:
    timeout: 30s
    
logging:
  level:
    com.embabel: INFO
    org.springframework.web: INFO
