server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: lax
        secure: false  # Set to true in production with HTTPS
        http-only: true

spring:
  application:
    name: meeting-planner-web-app
  config:
    import: "classpath:agent-application.yml"

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  # OAuth2 Security Configuration
  security:
    oauth2:
      client:
        registration:
          meeting-planner:
            provider: meeting-planner
            client-id: meeting-planner-web
            client-secret: web-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/meeting-planner"
            scope: [ openid, profile, email, meeting.read, meeting.write ]
            client-name: "Meeting Planner Web App"
          location-mcp:
            provider: auth-server
            client-id: location-mcp
            client-secret: mcp-secret
#            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope: [ mcp.invoke ]
            client-name: "Location MCP Client"
        provider:
          meeting-planner:
            issuer-uri: http://auth-server:9000
            user-name-attribute: sub
          auth-server:
            token-uri: http://auth-server:9000/oauth2/token
            user-name-attribute: sub

# Embabel Agent Configuration
embabel:
  agent:
    timeout: 30s

logging:
  level:
    com.embabel: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.client: DEBUG
    org.rag4j.meetingplanner.webapp.SessionDebugFilter: INFO
    root: INFO
